import re


class NotificationTextCleaner:
    """
    Clean text extracted from government notifications.

    The cleaner is intentionally conservative.
    It removes obvious OCR/layout noise without
    changing potentially important government facts.
    """

    def clean(self, text: str) -> str:
        if not text:
            return ""

        text = text.replace("\x00", " ")

        # Normalize line endings.
        text = text.replace("\r\n", "\n")
        text = text.replace("\r", "\n")

        # Remove excessive spaces while preserving newlines.
        text = re.sub(
            r"[ \t]+",
            " ",
            text,
        )

        # Remove excessive blank lines.
        text = re.sub(
            r"\n{3,}",
            "\n\n",
            text,
        )

        # Remove spaces immediately around newlines.
        text = re.sub(
            r" *\n *",
            "\n",
            text,
        )

        # Normalize common OCR dash variants.
        text = text.replace("–", "-")
        text = text.replace("—", "-")
        text = text.replace("-", "-")

        # Normalize repeated punctuation.
        text = re.sub(
            r"\.{4,}",
            "...",
            text,
        )

        # Remove obvious page markers generated by our OCR layer.
        text = re.sub(
            r"\[Page \d+\]\n?",
            "",
            text,
            flags=re.IGNORECASE,
        )

        return text.strip()

    def clean_lines(
        self,
        text: str,
    ) -> list[str]:
        """
        Return meaningful cleaned lines.
        """

        cleaned = self.clean(text)

        if not cleaned:
            return []

        lines = []

        for line in cleaned.split("\n"):
            line = line.strip()

            if line:
                lines.append(line)

        return lines