"""create initial PostgreSQL schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    uuid = lambda: postgresql.UUID(as_uuid=True)
    op.create_table("users", sa.Column("id", uuid(), primary_key=True), sa.Column("email", sa.String(320), nullable=False), sa.Column("password_hash", sa.String(255)), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table("user_profiles", sa.Column("id", uuid(), primary_key=True), sa.Column("user_id", uuid(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("full_name", sa.String(200), nullable=False), sa.Column("phone", sa.String(30)), sa.Column("dob", sa.Date()), sa.Column("category", sa.String(40)), sa.Column("gender", sa.String(20)), sa.Column("domicile_state", sa.String(100)), sa.Column("qualification", sa.String(100)), sa.Column("degree_name", sa.String(150)), sa.Column("stream", sa.String(150)), sa.Column("percentage_or_cgpa", sa.String(30)), sa.Column("additional_certs", sa.Text()), sa.Column("height_cm", sa.Integer()), sa.Column("preferred_categories", sa.Text()), sa.Column("preferred_states", sa.Text()), sa.Column("streak_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("last_checkin_date", sa.Date()), sa.Column("points", sa.Integer(), nullable=False, server_default="0"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_user_profiles_user_id", "user_profiles", ["user_id"], unique=True)
    op.create_table("jobs", sa.Column("id", uuid(), primary_key=True), sa.Column("title", sa.String(300), nullable=False), sa.Column("slug", sa.String(300), nullable=False), sa.Column("board", sa.String(200), nullable=False), sa.Column("board_code", sa.String(50), nullable=False), sa.Column("job_type", sa.String(30), nullable=False), sa.Column("state", sa.String(100), nullable=False), sa.Column("category", sa.String(100), nullable=False), sa.Column("post_name", sa.String(500), nullable=False), sa.Column("total_vacancies", sa.Integer(), nullable=False, server_default="0"), sa.Column("qualification_required", sa.String(150)), sa.Column("qualification_details", sa.Text()), sa.Column("min_age", sa.Integer()), sa.Column("max_age", sa.Integer()), sa.Column("notification_date", sa.Date()), sa.Column("start_date", sa.Date()), sa.Column("last_date", sa.Date()), sa.Column("exam_date", sa.String(100)), sa.Column("official_apply_url", sa.Text()), sa.Column("official_notification_pdf_url", sa.Text()), sa.Column("official_website_url", sa.Text()), sa.Column("salary_scale", sa.String(300)), sa.Column("status", sa.String(50), nullable=False, server_default="Open"), sa.Column("is_featured", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("is_new_today", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("is_closing_soon", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    for name in ["title","board","board_code","job_type","state","category","status"]: op.create_index(f"ix_jobs_{name}", "jobs", [name])
    op.create_index("ix_jobs_slug", "jobs", ["slug"], unique=True)
    op.create_table("job_eligibility", sa.Column("id", uuid(), primary_key=True), sa.Column("job_id", uuid(), sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("normalized_rules", postgresql.JSONB()), sa.Column("qualification_text", sa.Text()), sa.Column("experience_requirement", sa.Text()), sa.Column("service_requirement", sa.Text()), sa.Column("department_requirement", sa.Text()), sa.Column("special_requirements", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_job_eligibility_job_id", "job_eligibility", ["job_id"], unique=True)
    op.create_table("job_sources", sa.Column("id", uuid(), primary_key=True), sa.Column("job_id", uuid(), sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("organization", sa.String(200)), sa.Column("official_url", sa.Text(), nullable=False), sa.Column("notification_pdf_url", sa.Text()), sa.Column("source_type", sa.String(50), nullable=False, server_default="official"), sa.Column("last_checked_at", sa.DateTime(timezone=True)), sa.Column("last_processed_at", sa.DateTime(timezone=True)), sa.Column("content_hash", sa.String(128)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_job_sources_job_id", "job_sources", ["job_id"], unique=True)
    op.create_index("ix_job_sources_content_hash", "job_sources", ["content_hash"])
    op.create_table("application_trackers", sa.Column("id", uuid(), primary_key=True), sa.Column("user_id", uuid(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("job_id", uuid(), sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(40), nullable=False, server_default="saved"), sa.Column("application_number", sa.String(150)), sa.Column("roll_number", sa.String(150)), sa.Column("exam_center", sa.String(300)), sa.Column("applied_date", sa.Date()), sa.Column("exam_date", sa.String(100)), sa.Column("notes", sa.Text()), sa.Column("reminder_enabled", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    for name in ["user_id","job_id","status"]: op.create_index(f"ix_application_trackers_{name}", "application_trackers", [name])

def downgrade():
    op.drop_table("application_trackers"); op.drop_table("job_sources"); op.drop_table("job_eligibility"); op.drop_table("jobs"); op.drop_table("user_profiles"); op.drop_table("users")
