"""add job eligibility

Revision ID: 14e530c2fc9e
Revises: 6f3b18f21b81
Create Date: 2026-08-24 13:10:45.468752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e530c2fc9e'
down_revision: Union[str, Sequence[str], None] = '6f3b18f21b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_eligibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('minimum_age', sa.Integer(), nullable=True),
    sa.Column('maximum_age', sa.Integer(), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('degree', sa.String(length=150), nullable=True),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('minimum_experience_years', sa.Integer(), nullable=False),
    sa.Column('eligible_states', sa.String(length=500), nullable=True),
    sa.Column('eligible_categories', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_eligibility_id'), 'job_eligibility', ['id'], unique=False)
    op.create_index(op.f('ix_job_eligibility_job_id'), 'job_eligibility', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_eligibility_job_id'), table_name='job_eligibility')
    op.drop_index(op.f('ix_job_eligibility_id'), table_name='job_eligibility')
    op.drop_table('job_eligibility')
    # ### end Alembic commands ###
