"""add job source fields

Revision ID: 5a4697cf7252
Revises: 79bad752c5da
Create Date: 2026-08-24 23:09:55.565436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4697cf7252'
down_revision: Union[str, Sequence[str], None] = '79bad752c5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source_name', sa.String(length=150), nullable=True))
    op.add_column('jobs', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=False)
    op.create_index(op.f('ix_jobs_source_name'), 'jobs', ['source_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_source_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_column('jobs', 'external_id')
    op.drop_column('jobs', 'source_name')
    # ### end Alembic commands ###
