"""add normalized eligibility rules

Revision ID: 73ef36fd8186
Revises: 845c1939abf1
Create Date: 2026-08-31 13:53:29.671030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ef36fd8186'
down_revision: Union[str, Sequence[str], None] = '845c1939abf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_eligibility', sa.Column('normalized_rules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_eligibility', 'normalized_rules')
    # ### end Alembic commands ###
