"""add job sources

Revision ID: 79bad752c5da
Revises: 14e530c2fc9e
Create Date: 2026-08-24 16:22:21.663427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bad752c5da'
down_revision: Union[str, Sequence[str], None] = '14e530c2fc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_id'), 'job_sources', ['id'], unique=False)
    op.create_index(op.f('ix_job_sources_is_active'), 'job_sources', ['is_active'], unique=False)
    op.create_index(op.f('ix_job_sources_name'), 'job_sources', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_sources_name'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_is_active'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_id'), table_name='job_sources')
    op.drop_table('job_sources')
    # ### end Alembic commands ###
